export enum NotificationTypeCode {
  ORDER_CREATED = 'ORDER_CREATED',
  SELLER_REGISTERED = 'SELLER_REGISTERED',
  COMMENT_CREATED = 'COMMENT_CREATED',
  COMMENT_ANSWERED = 'COMMENT_ANSWERED',
  PRODUCT_RATED = 'PRODUCT_RATED',
  SELLER_RATED = 'SELLER_RATED',
}
